### ISSUE TITLE
add ntopng.conf ?

### ISSUE THREAD

**Issue by ShagoY** [junquera/ntopng-docker#2]
Hi @junquera :)

First of all, thank you for this ntopng docker version!

I would like to add the file ntopng.conf "out of the box" without making any modifications (build, etc...), is it possible?

Regards.

**Comment by ShagoY** [comment]
Like https://github.com/junquera/ntopng-docker/commit/54f19b653b70759965c5feefbbdc8b8828e5a2bf

**Comment by junquera** [comment]
Of course! Sincerely I have ever used any "aditional option", and I never would have thought it.

Thank you!

**Comment by junquera** [comment]
Would you like to make the pull request?

**Comment by ShagoY** [comment]
docker-compose.yml : 
```
version: '3.2'
services:  
    ntopng:
        image: junquera/ntopng
        container_name: ntopng
        restart: unless-stopped
        network_mode: host
        volumes:
        - ./ntopng.conf:/ntop/ntopng.conf:ro
        environment:
        - CONFIG=/ntop/ntopng.conf
```
Or
`docker run --net=host -t -p 3000:3000 -e CONFIG=/ntop/ntopng.conf -v ./ntopng.conf:/ntop/ntopng.conf:ro junquera/ntopng
`
